version: '3.6'
services:
  webrun:
    image: webrun/tomcat85:latest   
    build: .
    environment:
      - ENV TZ=America/Bahia
    ports:
      - "8080:8080"
    volumes:
       # Webrun - Arquivos      
      - ./deploy/reports:/opt/webrun/reports
      - ./deploy/config:/opt/webrun/config
      - ./deploy/systems:/opt/webrun/systems

       # Tomcat - Configuracoes
      - ./deploy/storage:/opt/tomcat/storage
      - ./deploy/tomcat/conf:/usr/local/tomcat/conf
      - ./deploy/tomcat/logs:/opt/tomcat/logs
      - ./deploy/webapps/ROOT.war:/opt/tomcat/webapps/ROOT.war
     
    command: /opt/tomcat/bin/catalina.sh run
    #command: /bin/sh
    
    # deploy:
      # resources:
        # limits:
          # cpus: '0.001'
          # memory: 50M
        # reservations:
          # cpus: '0.0001'
          # memory: 20M
    # rm -f /usr/local/tomcat/webapps/ROOT &&
        
    