version: "2"
services:
 tomcat:
  image: "sc/webrun"
  ports:
   - 80:8080
   - 443:8443
  extra_hosts:
   - "app.somos.chat:10.1.1.2"
  volumes:
   - /home/somoschat/config:/opt/webrun/config
   - /home/somoschat/systems/somos:/opt/webrun/systems/somos
   - /home/somoschat/config/server.xml:/opt/tomcat/conf/server.xml
   - /home/somoschat/ssl:/opt/tomcat/ssl
   - /home/somoschat/storage:/opt/tomcat/storage
  command: ["./start.sh", "somos", "400"]
